from aoc2025.days.day7 import (
    answer,
    answer_part_two,
)


def test_answer():
    data = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
    """
    assert answer(data.strip()) == 21


def test_answer_part_two():
    data = """

    """
    assert answer_part_two(data.strip()) == 0
